<h3>Alumno: Daniela Parra García</h3>
<h3>Matricula: A01633687</h3>

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/IDSNlogo.png" width="300" alt="cognitiveclass.ai logo"  />
</center>


<h3> Get to Know a Numpy Array </h3>


You will use the numpy array <code>A</code> for the following questions.


In [1]:
import numpy as np
A=np.array([[11,12],[21,22],[31,32]])


1.  Find the type of `x` using the function `type()`.


In [3]:
type(A)

numpy.ndarray

<details><summary>Click here for the solution</summary>

```python
type(A)
```

</details>


2.  Find the shape of the array:


In [4]:
A.shape

(3, 2)

<details><summary>Click here for the solution</summary>

```python
A.shape
```

</details>


3.  Find the type of data in the array:


In [5]:
A.dtype

dtype('int32')

<details><summary>Click here for the solution</summary>

```python
A.dtype
```

</details>


4.  Find the second row of the numpy array <code>A</code>:


In [6]:
A[1]

array([21, 22])

<details><summary>Click here for the solution</summary>

```python
A[1]
```

</details>


<h3>Two Types of Multiplication</h3>


You will use the following numpy arrays for the next questions:


In [7]:
A=np.array([[11,12],[21,22]])
B=np.array([[1, 0],[0,1]])

1.  Multiply array <code>A</code> and <code>B</code>.


In [8]:
A*B

array([[11,  0],
       [ 0, 22]])

<details><summary>Click here for the solution</summary>

```python
C = A * B
C
```

</details>


2.  Perform matrix multiplication on array <code>A</code> and <code>B</code> (order will not matter in this case).


In [10]:
np.dot(A,B)

array([[11, 12],
       [21, 22]])

<details><summary>Click here for the solution</summary>

```python
Z = np.dot(A,B)
Z
```

</details>


**Numpy 2D Arrays - Questions**

How many rows are in the following numpy array?

A = np.array([[1,2],[3,4],[5,6],[7,8]])

In [11]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])
A

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Is it possible to perform the following operation?

A = np.array([[1,2],[3,4],[5,6],[7,8]])

B = np.array([[1,2,3],[4,5,6],[7,8,9]])

np.dot(A,B)

In [12]:

A = np.array([[1,2],[3,4],[5,6],[7,8]])

B = np.array([[1,2,3],[4,5,6],[7,8,9]])

np.dot(A,B)

<class 'ValueError'>: shapes (4,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

<hr>

<h3 align="center"> © IBM Corporation 2020. All rights reserved. <h3/>
